### ISSUE TITLE
Exception on "./vendor/bin/luya import"

### ISSUE THREAD

**Issue by serhey-svintsitskiy** [luyadev/luya-kickstarter#23]
```

49 migrations were applied.

Migrated up successfully.
sergey@sergey-sayulinuxmint ~/www/luya-common.loc $ ./vendor/bin/luya import
Exception 'yii\base\InvalidArgumentException' with message 'luya\cms\models\BlockGroup has no attribute named "groupLabel".'

in /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/db/BaseActiveRecord.php:526

Stack trace:
#0 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-module-admin/src/ngrest/plugins/Text.php(71): yii\db\BaseActiveRecord->setAttribute('groupLabel', '')
#1 [internal function]: luya\admin\ngrest\plugins\Text->onAssign(Object(yii\db\AfterSaveEvent))
#2 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\db\AfterSaveEvent))
#3 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/db/BaseActiveRecord.php(992): yii\base\Component->trigger('afterInsert', Object(yii\db\AfterSaveEvent))
#4 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/db/ActiveRecord.php(560): yii\db\BaseActiveRecord->afterSave(true, Array)
#5 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/db/ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#6 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#7 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(162): yii\db\BaseActiveRecord->save()
#8 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(87): luya\cms\admin\importers\BlockImporter->getBlockGroupId(Object(luya\cms\frontend\blocks\HtmlBlock))
#9 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(41): luya\cms\admin\importers\BlockImporter->saveBlock('\\luya\\cms\\front...')
#10 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-core/console/commands/ImportController.php(157): luya\cms\admin\importers\BlockImporter->run()
#11 [internal function]: luya\console\commands\ImportController->actionIndex()
#12 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#15 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#16 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('import', Array)
#17 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('import', Array)
#18 /home/sergey/www/luya-common.loc/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-core/base/Boot.php(205): yii\base\Application->run()
#20 /home/sergey/www/luya-common.loc/vendor/luyadev/luya-core/bin/luya(22): luya\base\Boot->applicationConsole()
#21    ###{main}```

**Comment by nadar** [comment]
I will check this, thanks for the report!

**Comment by nadar** [comment]
Yes i can confirm its a bug. Thanks will patch fix asap

**Comment by nadar** [comment]
please run composer update and try again. The patch release is done in luya module admin version 1.1.1.1 (what a cool release number).

Thanks for the report! If the problem is solved, you can close the issue.

**Comment by serhey-svintsitskiy** [comment]
Thank you. It works.
